services:
  web:
    build: .
    container_name: django_backend
    volumes:
      - .:/app
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      # - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      # - DB_HOST=postgres
      - DB_PORT=5432
      - REDIS_HOST=redis_cache
      - REDIS_PORT=6379
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8000:8000"
    depends_on:
      - redis_cache
      - postgres




volumes:
  postgres_data: