databases:
  - name: observatorio-db
    databaseName: observatorio
    user: observatorio
    plan: free

services:
  - type: web
    name: observatorio-backend
    runtime: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.9"
      - key: DATABASE_URL
        fromDatabase:
          name: observatorio-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"